### ISSUE TITLE
Testing on Android hardware

### ISSUE THREAD

**Issue by arronhunt** [arronhunt/react-native-emoji-selector#1]
Looking for testers to help test this library on physical Android devices and submit PRs against them.

**Comment by reggie3** [comment]
I'm using Android.  Thanks for making this component.  I'll provide what help I can with your Android testing.

**Comment by shimatai** [comment]
I Android, the emoji icons are showing too big. I can help you, cause I have a lot of Android hardware. I will fork your project and fix for Android.

**Comment by arronhunt** [comment]
@shimatai Could you share a screenshot? You can adjust the sizes of the icons by using the `columns` prop. Default is `6`
