### ISSUE TITLE
Recently used empty

### ISSUE THREAD

**Issue by mmckinley8** [arronhunt/react-native-emoji-selector#11]
How can I populate the recently used tab? Additionally I'd like to default to that tab on render...it doesn't appear as a Category.

Awesome library - nice work!

**Comment by arronhunt** [comment]
This could possibly be related to #9 but I wasn’t able to replicate the warning there. 

Adding “History” as an initial tab should be relatively painless, I’ll try to push a version bump to include this.

**Comment by arronhunt** [comment]
Hey @mmckinley8 are you still seeing this issue?

**Comment by NateRickard** [comment]
This is still an issue along with #9. RN 0.61

Without setting `showHistory={true}` the recently used tab would show up but never be populated. Adding `showHistory={true}` triggers the warning that AsyncStorage has been moved to https://github.com/react-native-community/async-storage

[This article](https://pusher.com/tutorials/gifs-emojis-react-native-chat) uses your component and has a purple box about 1/2 way down that details the issue. Copying the code locally and making the adjustment to the `import` statement (after installing the npm package) does indeed make the warning go away and the history starts working.

**Comment by arronhunt** [comment]
Closing in favor of #9 I'll look into this today
