### ISSUE TITLE
Activity Indicator Doesn't Go Away Even After Emojis are Available

### ISSUE THREAD

**Issue by reggie3** [arronhunt/react-native-emoji-selector#2]
When opening the component, the ActivityIndicator doesn't go away even though the emojis get loaded.  I can the tell that the emojis get loaded because I can click a category while the ActivityIndicator is being displayed, and see the categories emojis.

**Comment by reggie3** [comment]
I think this behavior is being caused by `shouldComponentUpdate` in the selector component.  The way the if statement is currently built, a change to `isReady` is ignored, and the component won't update.  I changed the conditional statement to include `isReady`, and the result was that no `ActivityIndicator` was displayed, and a slightly delayed rendering of the emojis.

**Comment by arronhunt** [comment]
Thanks for the report @reggie3. I opted to remove the entire `shouldComponentUpdate` method. If there's noticeable performance hits from re-renders in the future I may consider adding it back. 

Published v0.1.5 to npm
