### ISSUE TITLE
Android 7

### ISSUE THREAD

**Issue by sshmyg** [arronhunt/react-native-emoji-selector#27]
Hi, there are some empty and broken cells in selector on android 7 version

![image](https://user-images.githubusercontent.com/1410608/69856751-01eea480-1297-11ea-9631-d09327830d0d.png)

**Comment by arronhunt** [comment]
Hey @sshmyg, can you checkout v0.1.8 and let me know if you are still seeing this issue?

**Comment by jayeshghyperlink** [comment]
@arronhunt  facing same issue with version 0.1.8 kindly find pictures 
![dependecy](https://user-images.githubusercontent.com/61151295/74834519-94a45a00-5341-11ea-89e5-81dde13098e5.png)
![emoji-issue](https://user-images.githubusercontent.com/61151295/74834531-99690e00-5341-11ea-9fe4-07504e78a28a.png)

**Comment by arronhunt** [comment]
As Dror-Bar [pointed out](https://github.com/arronhunt/react-native-emoji-selector/issues/5#issuecomment-511199310) it appears to be the emojis with gender variants that are stacking/overlapping. The missing ones I'm assuming are because that emoji doesn't exist in that version of Android.

**Comment by nijat13** [comment]
@arronhunt did you find anything?

**Comment by evertoncunha** [comment]
Check here https://github.com/arronhunt/react-native-emoji-selector/issues/28#issuecomment-630392573

**Comment by arronhunt** [comment]
Closing this out, please check #40 :)
