### ISSUE TITLE
Missing Emojis

### ISSUE THREAD

**Issue by tagqcmanager** [arronhunt/react-native-emoji-selector#28]
On certain devices, specially the older ones, few emojis seem to missing. This may be because of the font handling of how Andorid does. Can you please help in how to handle this situation by restricting the emojis to basic types so that all emojis appear excluding the ones which may be missing?

Regards,
Iftikhar

**Comment by RajeshKumDev** [comment]
Same issue here. Please suggest something.

**Comment by huyhai** [comment]
same

**Comment by nijat13** [comment]
same

**Comment by evertoncunha** [comment]
This may helps: https://github.com/arronhunt/react-native-emoji-selector/pull/40

with: 

```js
const emojiVersion = (() => {
  const version = parseFloat(Platform.Version)
  if (Platform.OS === 'ios') {
    return version < 13.2 ? 11 : 12.1
  }
  if (Platform.OS === 'android') {
    return version < 29 ? 11 : 12.1
  }
})()

const hasImageOS = `has_img_${Platform.OS === 'ios' ? 'apple' : 'google'}`

<EmojiSelector
    ...
    shouldInclude={e => parseFloat(e['added_in']) <= emojiVersion && e[hasImageOS] === true}
/>
```

**Comment by ralppppy** [comment]
Is there any update on this?

**Comment by arronhunt** [comment]
Closing this out, please check #40 :)
