### ISSUE TITLE
Change Emoji Hieght and width

### ISSUE THREAD

**Issue by Parthhyperlink** [arronhunt/react-native-emoji-selector#36]
Hi, this is awesome library but the emoji layout is quite big, how can change a height and width of emoji?

**Comment by arronhunt** [comment]
Hey @Parthhyperlink. You can set the overall size by changing the number of columns. The default is 6

```
import EmojiSelector from "react-native-emoji-selector";

<EmojiSelector
  columns={12}
  onEmojiSelected={handleEmoji}
/>;
```

**Comment by arronhunt** [comment]
Closing for now, if this doesn't solve your problem I can reopen the ticket
