### ISSUE TITLE
Resizing Emoji Icon

### ISSUE THREAD

**Issue by DilipCoder** [arronhunt/react-native-emoji-selector#39]
Hey,
I am facing an issue about emoji resizing. Its showing me a very large emoji Icons

![Issue](https://user-images.githubusercontent.com/25370616/81058906-07f34c00-8eed-11ea-9e8b-4b41558c7fb6.png)

**Comment by arronhunt** [comment]
Hey @DilipCoder you can change the number of emojis across by using the `columns` prop

```jsx
<EmojiSelector
  columns={10}
/>
```
