### ISSUE TITLE
Missing  i18n Implementation

### ISSUE THREAD

**Issue by CryceTruly** [arronhunt/react-native-emoji-selector#43]
### Description

When passing Categories, it would be good to customize which text is displayed depending on the current user language preference.

It would be good to pass a prop like i18n={{ search: 'Recherche', categories: { search: 'Résultats de recherche', recent: 'Récents' } }}

**Comment by arronhunt** [comment]
Duplicate #15 

If anyone wants to contribute by setting up i18n in a PR I think a lot of people would appreciate :)
