### ISSUE TITLE
STYLING EMOJI SIZE

### ISSUE THREAD

**Issue by vismayainnow8** [arronhunt/react-native-emoji-selector#47]
Is it possible to change the size of all the emojis in the categories.. because i think emojis size in the categories bar  and emoji size in the categories content id different ...one is small and the other is big

**Comment by arronhunt** [comment]
Hi @vismayainnow8, can you please let me know what behavior you are expecting and not seeing?

**Comment by vismayainnow8** [comment]
> Hi @vismayainnow8, can you please let me know what behavior you are expecting and not seeing?

i need both to be small

**Comment by arronhunt** [comment]
Both of what? You can change the size of the emoji grid by passing in the columns prompt. 

```jsx
<EmojiSelector
  columns={8}
  onEmojiSelected={handleEmojiSelect}
/>;
```

The more columns you have the smaller size the emoji previews become.
