### ISSUE TITLE
Demo for displaying emoji

### ISSUE THREAD

**Issue by phillip9077** [arronhunt/react-native-emoji-selector#52]
Hi, could you add the sample code from your demo so we can see how to properly display the emoji in a View? It would help in addition to just having code that logs an emoji in the console. Thank you!

**Comment by arronhunt** [comment]
Hi @phillip9077, the emoji data you get back from the component can be treated exactly like a text string :)

```jsx
const [selectedEmoji, setSelectedEmoji] = React.useState('');

<View>
  <Text>
    The emoji you picked was: {selectedEmoji}
  </Text>
  <EmojiSelector onEmojiSelected={emoji => setSelectedEmoji(emoji)} />
</View>
```

**Comment by phillip9077** [comment]
Oh okay!. That is very simple and helpful. Thank you!
