### ISSUE TITLE
Emoji sizes are rapidy and contionous increasing size till the app crushed

### ISSUE THREAD

**Issue by lylest** [arronhunt/react-native-emoji-selector#54]
Emoji sizes are rapidy and contionous increasing size till the app crushed

**Comment by arronhunt** [comment]
@lylest Can you provide more details about your code? This sounds like some sort of react hook infinite loop.

**Comment by lylest** [comment]
Fixed it by how do I resolve emoji which are not found they show little box icons

**Comment by arronhunt** [comment]
This fix should help you with hiding missing emojis https://github.com/arronhunt/react-native-emoji-selector/pull/40
